--UPDATE FAT_TTABTIPLOG
--   SET CODTIPLOGCOM = @CODCOMERCIAL
--WHERE CODTIPLOG = @COD_PROFAT  
UPDATE FAT_TTABTIPLOG
   SET DESTIPLOG = @CODCOMERCIAL,
       CODUSU = 100,  -- IVA
	   DATULTALT = GETDATE()
WHERE CODTIPLOG = @COD_PROFAT  
