--UPDATE FAT_TTABTIPLOG
--   SET CODTIPLOGCOM = @CODCOMERCIAL
--WHERE CODTIPLOG = @COD_PROFAT  
UPDATE FAT_TTABTIPLOG
   SET DESTIPLOG = @CODCOMERCIAL,
       CODUSU = 1100,  -- INTEGRAÇÕES
	   DATULTALT = GETDATE()
WHERE CODTIPLOG = @COD_PROFAT  
