--INSERE NOVAS DIVISÕES NO NOVI
INSERT INTO ADA_OTARI
(ODIVI_COD_DIVI, ODIVI_NOC_DIVI, ODIVI_NOL_DIVI, ODIVI_USU_ULTACTU, ODIVI_FEC_ULTACTU, ODIVI_HOR_ULTACTU, ODIVI_COD_OPERATIV, ODIVI_COD_ERP, COD_COMERCIAL)
VALUES 
(:ODIVI_COD_DIVI, :ODIVI_NOC_DIVI, :ODIVI_NOL_DIVI, 'OM13', TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HH24MISS'), 'VI', NULL, :COD_COMERCIAL)