--RECUPERA DADOS DO PROFAT DE TIPO DE SERVIÇO E FAMILIA DE SERVIÇO
SELECT TIPSER.CODTIPSER, TIPSER.DESSER , CODITECOB, CODSEGCOM, FAM.CODFAM, FAM.DESFAM
FROM FAT_TCADTIPSER AS TIPSER WITH(NOLOCK) 
       INNER JOIN FAT_TCADSUBSEG AS SUBSEG WITH(NOLOCK) ON TIPSER.CODSUBSEG = SUBSEG.CODSUBSEG 
       INNER JOIN FAT_TCADSEG AS SEG WITH(NOLOCK) ON SUBSEG.CODSEG = SEG.CODSEG 
												 AND SEG.CODDIV = 2 
       INNER JOIN DBO.FAT_TTABFAM AS FAM WITH(NOLOCK) ON FAM.CODSEG = SUBSEG.CODSEG 
       INNER JOIN FAT_TCADITECOB WITH(NOLOCK) ON FAT_TCADITECOB.CODTIPSER = TIPSER.CODTIPSER
WHERE 1=1
  and TIPSER.CODTIPSER = @CODTIPSER
  --and CODSEGCOM = 'V180'