--OBTEM DADOS DO MARTE
SELECT COD_MARTE, COD_PROFAT, COD_NOVI, OTARI_COD_COMPO, COD_COMERCIAL 
FROM MARTE.VABR_TDE_PARA_GERAL 
     INNER JOIN DDLVIG.OTARI ON VABR_TDE_PARA_GERAL.COD_NOVI = OTARI.OTARI_COD_COMPO
     INNER JOIN MARTE.COPR_TPRODUCTO ON VABR_TDE_PARA_GERAL.COD_MARTE = COPR_TPRODUCTO.COD_PRODUCTO
WHERE COD_PARAM_TAB = 9
ORDER BY COD_MARTE
