--ATUALIZA CLIENTE NOVI
UPDATE DDLVIG.OCLTE
   SET OCLTE_COD_NIF = :COD_IDENTIFICACION_FISCAL,
	   OCLTE_NOC_CLIENTE = :DES_NOMBRE_FANTASIA,
	   OCLTE_NOL_CLIENTE = :DES_RAZON_SOCIAL,
	   OCLTE_USU_ULTACTU = 'OM13',
	   OCLTE_FEC_ULTACTU =  TO_CHAR(SYSDATE, 'YYYYMMDD'),
	   OCLTE_HOR_ULTACTU = TO_CHAR(SYSDATE, 'HH24MISS'),
	   OCLTE_COD_VIA = :OCLTE_COD_VIA,
	   COD_CLIENTE_COMERCIAL = :COD_COMERCIAL	
WHERE OCLTE_COD_CLIENTE = :COD_NOVI