SELECT C.COD_CLIENTE, C.DES_RAZON_SOCIAL, COD_IDENTIFICACION_FISCAL
FROM MARTE.COPR_TCLIENTE C INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON C.COD_CLIENTE = V.COD_MARTE     
WHERE C.BOL_POTENCIAL = 0    
  AND V.COD_PARAM_TAB = '10'
  AND C.COD_IDENTIFICACION_FISCAL IS NULL