INSERT INTO COPR_TDELEGACION
(OID_DELEGACION, COD_DELEGACION, DES_DELEGACION, DES_CORTA_DELEGACION, BOL_ACTIVO, OID_ZONAGERENCIAL, OID_PAIS, FYH_CDATE, DES_CUID)
VALUES
(:OID_DELEGACION, :COD_DELEGACION, :DES_DELEGACION, :DES_CORTA_DELEGACION, 1, 'CAC19C1C0E4D13A7E040007F01003FD5        ', '55                                      ', SYSDATE(), 'OM13')