UPDATE DDLVIG.ODERE
SET ODERE_COD_REG = :COD_PROFAT,
	ODERE_USU_ULTACTU = 'OM13',
	ODERE_FEC_ULTACTU = TO_CHAR(SYSDATE, 'YYYYMMDD'), 
	ODERE_HOR_ULTACTU = TO_CHAR(SYSDATE, 'HH24MISS')
WHERE TRIM(ODERE_COD_REG) = (SELECT TRIM(OREGI_COD_REG) FROM DDLVIG.OREGI WHERE TRIM(OREGI_NOC_REG) = :UF_PROFAT AND (TRIM(OREGI_NOL_REG) = :DES_PROFAT OR TRIM(OREGI_NOL_REG) = :DES_PROFAT2))