--VERIFICA NIF DUPLICADO
SELECT COUNT(S.COD_IDENTIFICACION_FISCAL) QTD, S.COD_IDENTIFICACION_FISCAL
FROM MARTE.COPR_TSUBCLIENTE S INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON V.COD_MARTE = S.OID_SUBCLIENTE
WHERE V.COD_PARAM_TAB = '11'
  AND S.BOL_ES_PTO_FACTURACION = 1
GROUP BY S.COD_IDENTIFICACION_FISCAL
HAVING COUNT(S.COD_IDENTIFICACION_FISCAL) > 1