--VERIFICA NIF NULO
SELECT C.COD_CLIENTE, S.COD_SUBCLIENTE, C.COD_IDENTIFICACION_FISCAL NIF_CLIENTE, S.COD_IDENTIFICACION_FISCAL NIF_SUBCLIENTE
FROM MARTE.COPR_TCLIENTE C INNER JOIN MARTE.COPR_TSUBCLIENTE S ON C.OID_CLIENTE = S.OID_CLIENTE
     INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON V.COD_MARTE = S.OID_SUBCLIENTE
WHERE V.COD_PARAM_TAB = '11'
  AND S.BOL_ES_PTO_FACTURACION = 1
  AND S.COD_IDENTIFICACION_FISCAL IS NULL
ORDER BY 1, 2 