SELECT
    (SELECT DES_VALOR
     FROM
         MARTE.COPR_TVALOR_ATRIBUTOXSUBCLI_CO
         INNER JOIN MARTE.GEPR_TATRIBUTO
                ON  COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_ATRIBUTO = GEPR_TATRIBUTO.OID_ATRIBUTO
         INNER JOIN MARTE.COPR_TPARAMETRO
                ON  GEPR_TATRIBUTO.COD_ATRIBUTO = COPR_TPARAMETRO.VALOR
     WHERE
         COPR_TPARAMETRO.COD_PARAMETRO = 'ATBC_EMAIL_SUB'
     AND COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_SUBCLIENTE = COPR_TSUBCLIENTE.OID_SUBCLIENTE) AS EmailResponsavelNF
,   (SELECT DES_VALOR
     FROM
         MARTE.COPR_TVALOR_ATRIBUTOXSUBCLI_CO
         INNER JOIN MARTE.GEPR_TATRIBUTO
                ON  COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_ATRIBUTO = GEPR_TATRIBUTO.OID_ATRIBUTO
         INNER JOIN MARTE.COPR_TPARAMETRO
                ON  GEPR_TATRIBUTO.COD_ATRIBUTO = COPR_TPARAMETRO.VALOR
     WHERE
         COPR_TPARAMETRO.COD_PARAMETRO = 'ATBC_NFDEST_SUB'
     AND COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_SUBCLIENTE = COPR_TSUBCLIENTE.OID_SUBCLIENTE) AS NomeResponsavelNF
,   (SELECT DES_VALOR
     FROM
         MARTE.COPR_TVALOR_ATRIBUTOXSUBCLI_CO
         INNER JOIN MARTE.GEPR_TATRIBUTO
                ON  COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_ATRIBUTO = GEPR_TATRIBUTO.OID_ATRIBUTO
         INNER JOIN MARTE.COPR_TPARAMETRO
                ON  GEPR_TATRIBUTO.COD_ATRIBUTO = COPR_TPARAMETRO.VALOR
     WHERE
         COPR_TPARAMETRO.COD_PARAMETRO = 'ATBC_MDDEST_SUB'
     AND COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_SUBCLIENTE = COPR_TSUBCLIENTE.OID_SUBCLIENTE) AS DestinatarioMalaDireta
,   (SELECT DES_VALOR
     FROM
         MARTE.COPR_TVALOR_ATRIBUTOXSUBCLI_CO
         INNER JOIN MARTE.GEPR_TATRIBUTO
                ON  COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_ATRIBUTO = GEPR_TATRIBUTO.OID_ATRIBUTO
         INNER JOIN MARTE.COPR_TPARAMETRO
                ON  GEPR_TATRIBUTO.COD_ATRIBUTO = COPR_TPARAMETRO.VALOR
     WHERE
      COPR_TPARAMETRO.COD_PARAMETRO = 'ATBC_DPTO_SUB'
     AND COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_SUBCLIENTE = COPR_TSUBCLIENTE.OID_SUBCLIENTE) AS DepartamentoMalaDireta
,   (SELECT DES_VALOR
     FROM
         MARTE.COPR_TVALOR_ATRIBUTOXSUBCLI_CO
         INNER JOIN MARTE.GEPR_TATRIBUTO
                ON  COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_ATRIBUTO = GEPR_TATRIBUTO.OID_ATRIBUTO
         INNER JOIN MARTE.COPR_TPARAMETRO
                ON  GEPR_TATRIBUTO.COD_ATRIBUTO = COPR_TPARAMETRO.VALOR
     WHERE
         COPR_TPARAMETRO.COD_PARAMETRO = 'ATBC_MES_REAJUSTE'
     AND COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_SUBCLIENTE = COPR_TSUBCLIENTE.OID_SUBCLIENTE) AS MesReajuste
FROM MARTE.COPR_TSUBCLIENTE
     INNER JOIN MARTE.COPR_TCLIENTE ON COPR_TCLIENTE.OID_CLIENTE = COPR_TSUBCLIENTE.OID_CLIENTE
WHERE MARTE.COPR_TCLIENTE.OID_CLIENTE = :CLIENTE
  AND COD_SUBCLIENTE = :SUBCLIENTE
