SELECT S.COD_SUBCLIENTE COD_SUB_MARTE
	   ,S.OID_CLIENTE
       ,O.OSBCL_COD_CLIENTE COD_CLI_NOVI
       ,O.OSBCL_COD_SUBCLI COD_SUB_NOVI
       ,V.COD_PROFAT
       ,S.OID_TIPO_ID_FISCAL
       ,S.COD_IDENTIFICACION_FISCAL
       ,S.DES_SUBCLIENTE
       ,S.DES_CORTA_SUBCLIENTE
       ,S.COD_INSCRIPCION_ESTATAL
       ,S.COD_INSCRIPCION_MUNICIPAL
       ,D.COD_CEP
       ,D.DES_CALLE
       ,D.NUM_NRO
       ,D.DES_COMPL_DIRECCION
       ,L.COD_TIPO_CALLE
       ,L.DES_TIPO_CALLE
       ,D.DES_BARRIO
       ,CI.DES_CIUDAD
       ,TRIM(CI.OID_ESTADO) as ESTADO
       ,F.DES_FILIAL
       ,TS.COD_TIPO_SUBCLIENTE
       ,TS.DES_TIPO_SUBCLIENTE  
       ,S.BOL_ACTIVO   
FROM MARTE.COPR_TSUBCLIENTE S
INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON V.COD_MARTE = S.OID_SUBCLIENTE
 LEFT JOIN DDLVIG.OSBCL O ON V.COD_NOVI = O.OSBCL_COD_CLIENTE ||'/' || O.OSBCL_COD_SUBCLI
 LEFT JOIN MARTE.COPR_TDOMICILIOXSUBCLI DS ON S.OID_SUBCLIENTE = DS.OID_SUBCLIENTE
 LEFT JOIN MARTE.COPR_TDOMICILIO D ON DS.OID_DOMICILIO = D.OID_DOMICILIO
 LEFT JOIN MARTE.COPR_TTIPO_CALLE L ON D.OID_TIPO_CALLE = L.OID_TIPO_CALLE
 LEFT JOIN MARTE.COPR_TCIUDAD CI ON D.OID_CIUDAD = CI.OID_CIUDAD
 LEFT JOIN MARTE.COPR_TFILIAL F ON S.OID_FILIAL_COMERCIAL = F.OID_FILIAL
 LEFT JOIN MARTE.COPR_TTIPO_SUBCLIENTE TS ON S.OID_TIPO_SUBCLIENTE = TS.OID_TIPO_SUBCLIENTE
WHERE V.COD_PARAM_TAB = '11'
ORDER BY V.COD_PROFAT