--DELETA LIXO DA TABELA DO DEPARA
DELETE FROM MARTE.VABR_TDE_PARA_GERAL 
WHERE COD_PARAM_TAB = '7'
  AND COD_MARTE NOT IN (SELECT A.COD_MARTE
                        FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
                        WHERE A.COD_PARAM_TAB = '7')