--DELETA LIXO DA TABELA DO NOVI
DELETE FROM ADA_XELEM X
WHERE X.XELEM_COD_TABLA = '59'
  AND X.XELEM_COD_IDIOMA = '55'
  AND X.XELEM_COD_ATRIBUTO = 2
  AND X.XELEM_COD_ELEMENTO NOT IN (SELECT A.COD_NOVI
                                   FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
                                   WHERE A.COD_PARAM_TAB = '7')