--BUSCA CIDADE NO MARTE QUE NÃO ESTÃO NO DEPARA
SELECT C.OID_ESTADO, C.COD_CIUDAD, C.DES_CIUDAD
FROM MARTE.COPR_TCIUDAD C
WHERE C.COD_CIUDAD NOT IN (SELECT A.COD_MARTE
							FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
							WHERE A.COD_PARAM_TAB = '7')