--BUSCA DADOS PARA NORMALIZAÇÃO
SELECT A.COD_MARTE, A.COD_PROFAT, A.COD_NOVI
FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
WHERE A.COD_PARAM_TAB = '7'
ORDER BY A.COD_PROFAT DESC