--ATUALIZA COD IBGE NO NOVI
--UPDATE ADA_XELEM
UPDATE XELEM
   SET COD_COMERCIAL = :COD_IBGE
WHERE XELEM_COD_TABLA = '59'
  AND XELEM_COD_IDIOMA = '55'
  AND XELEM_COD_ELEMENTO = :COD_CIUDAD	
  AND XELEM_COD_ATRIBUTO = 2
  AND XELEM_COD_DELEGA = '00'