MERGE INTO dbo.FAT_TCADFUNPAT PAT1
 USING (SELECT 'PAR1' CODFUNPAT, 'PAR2' DESFUNPAT, 'PAR3' CODFUNPATCOM) PAT2 
 ON (PAT1.CODFUNPAT = PAT2.CODFUNPAT)
 WHEN MATCHED THEN 
      UPDATE SET DATULTALT = GETDATE(), CODUSU = 100, DESFUNPAT = PAT2.DESFUNPAT, CODFUNPATCOM = PAT2.CODFUNPATCOM
 WHEN NOT MATCHED THEN 
      INSERT (CODFUNPAT, DESFUNPAT, CODUSU, DATULTALT, CODFUNPATCOM)
      VALUES (PAT2.CODFUNPAT, PAT2.DESFUNPAT, 100, GETDATE(), PAT2.CODFUNPATCOM);