SELECT P.COD_TIPO_PUESTO COD_COMERCIAL, P.DES_TIPO_PUESTO, V.COD_NOVI
FROM MARTE.COPR_TTIPO_PUESTO P
INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON P.COD_TIPO_PUESTO = V.COD_MARTE
INNER JOIN DDLVIG.XELEM X ON X.XELEM_COD_ELEMENTO =  V.COD_NOVI
WHERE V.COD_PARAM_TAB = '8'
  AND X.XELEM_COD_TABLA = '73'
  AND X.XELEM_COD_IDIOMA = '55'
  AND XELEM_COD_ATRIBUTO = 2
  --AND P.BOL_ACTIVO = 1
ORDER BY 1