UPDATE DDLVIG.XELEM
   SET COD_COMERCIAL = :COD_COMERCIAL,
       XELEM_USU_ULTACTU = 'OM13',
       XELEM_FEC_ULTACTU = TO_CHAR(SYSDATE, 'YYYYMMDD'),
       XELEM_HOR_ULTACTU = TO_CHAR(SYSDATE, 'HH24MISS')
WHERE XELEM_COD_TABLA = '73'
  AND XELEM_COD_IDIOMA = 55
  AND XELEM_COD_ATRIBUTO IN (2,3,4)
  AND XELEM_COD_ELEMENTO = :COD_NOVI