'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Prosegur.OM13.Migracao.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to alter table &quot;MARTE&quot;.&quot;COPR_TCIUDAD&quot; disable all triggers.
        '''</summary>
        Friend ReadOnly Property ALTER_TABLE_MARTE_DESABILITA_TRIGGER() As String
            Get
                Return ResourceManager.GetString("ALTER_TABLE_MARTE_DESABILITA_TRIGGER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to alter table &quot;MARTE&quot;.&quot;COPR_TCIUDAD&quot; enable all triggers.
        '''</summary>
        Friend ReadOnly Property ALTER_TABLE_MARTE_HABILITA_TRIGGER() As String
            Get
                Return ResourceManager.GetString("ALTER_TABLE_MARTE_HABILITA_TRIGGER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA CLIENTE NOVI
        '''UPDATE DDLVIG.OCLTE
        '''   SET OCLTE_COD_NIF = :COD_IDENTIFICACION_FISCAL,
        '''	   OCLTE_NOC_CLIENTE = :DES_NOMBRE_FANTASIA,
        '''	   OCLTE_NOL_CLIENTE = :DES_RAZON_SOCIAL,
        '''	   OCLTE_USU_ULTACTU = &apos;OM13&apos;,
        '''	   OCLTE_FEC_ULTACTU =  TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;),
        '''	   OCLTE_HOR_ULTACTU = TO_CHAR(SYSDATE, &apos;HH24MISS&apos;),
        '''	   OCLTE_COD_VIA = :OCLTE_COD_VIA,
        '''	   COD_CLIENTE_COMERCIAL = :COD_COMERCIAL	
        '''WHERE OCLTE_COD_CLIENTE = :COD_NOVI.
        '''</summary>
        Friend ReadOnly Property ATUALIZA_NOVI_ATUALIZACLIENTE() As String
            Get
                Return ResourceManager.GetString("ATUALIZA_NOVI_ATUALIZACLIENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA A DIVISÃO COM O CODIGO COMERCIAL
        '''UPDATE ADA_OTARI
        '''   SET COD_COMERCIAL = :COD_COMERCIAL
        '''WHERE OTARI_COD_COMPO = :COD_DIV.
        '''</summary>
        Friend ReadOnly Property ATUALIZA_NOVI_DIVISAOCODCOMERCIAL() As String
            Get
                Return ResourceManager.GetString("ATUALIZA_NOVI_DIVISAOCODCOMERCIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA SUB CLIENTE NOVI
        '''UPDATE DDLVIG.OSBCL
        '''   SET OSBCL_NOC_SUBCLI = :OSBCL_NOC_SUBCLI, 
        '''	   OSBCL_NOL_SUBCLI = :OSBCL_NOL_SUBCLI, 
        '''       OSBCL_USU_ULTACTU = &apos;OM13&apos;,
        '''	   OSBCL_FEC_ULTACTU = TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;),
        '''	   OSBCL_HOR_ULTACTU = TO_CHAR(SYSDATE, &apos;HH24MISS&apos;), 
        '''	   OSBCL_COD_VIA = :OSBCL_COD_VIA, 
        '''	   COD_SUBCLI_COMERCIAL = :COD_COMERCIAL
        '''WHERE OSBCL_COD_CLIENTE = :COD_CLIE
        '''  AND OSBCL_COD_SUBCLI = :COD_SUBCLIE.
        '''</summary>
        Friend ReadOnly Property ATUALIZA_NOVI_SUBCLIENTE() As String
            Get
                Return ResourceManager.GetString("ATUALIZA_NOVI_SUBCLIENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA CLIENTE PROFAT
        '''UPDATE FAT_TCADCLI
        '''   SET CODCLICOM = @COD_COMERCIAL
        '''WHERE CODCLI = @COD_PROFAT .
        '''</summary>
        Friend ReadOnly Property ATUALIZA_PROFAT_ATUALIZACLIENTE() As String
            Get
                Return ResourceManager.GetString("ATUALIZA_PROFAT_ATUALIZACLIENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA O ITEM DE COBRANÇA COM O CODIGO COMERCIAL
        '''UPDATE FAT_TCADITECOB
        '''   SET CODSEGCOM = @CODSEGCOM
        '''WHERE CODITECOB = @CODITECOB.
        '''</summary>
        Friend ReadOnly Property ATUALIZA_PROFAT_DIVISAOCODCOMERCIAL() As String
            Get
                Return ResourceManager.GetString("ATUALIZA_PROFAT_DIVISAOCODCOMERCIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA SUB CLIENTE PROFAT
        '''UPDATE FAT_TCADPONATE
        '''   SET CODPONATECOM = @COD_COMERCIAL
        '''WHERE CODPONATE = @COD_PROFAT .
        '''</summary>
        Friend ReadOnly Property ATUALIZA_PROFAT_SUBCLIENTE() As String
            Get
                Return ResourceManager.GetString("ATUALIZA_PROFAT_SUBCLIENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --DELETA LIXO DA TABELA DO DEPARA
        '''DELETE FROM MARTE.VABR_TDE_PARA_GERAL 
        '''WHERE COD_PARAM_TAB = &apos;7&apos;
        '''  AND COD_MARTE NOT IN (SELECT A.COD_MARTE
        '''                        FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
        '''                        WHERE A.COD_PARAM_TAB = &apos;7&apos;).
        '''</summary>
        Friend ReadOnly Property DELETE_DEPARA_CIDADESEMDEPARA() As String
            Get
                Return ResourceManager.GetString("DELETE_DEPARA_CIDADESEMDEPARA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM MARTE.VABR_TDE_PARA_GERAL
        '''WHERE COD_PARAM_TAB = &apos;5&apos;
        '''.
        '''</summary>
        Friend ReadOnly Property DELETE_DEPARA_DELETADELEGACAO() As String
            Get
                Return ResourceManager.GetString("DELETE_DEPARA_DELETADELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM MARTE.VABR_TDE_PARA_GERAL
        '''WHERE COD_PARAM_TAB = &apos;6&apos;
        '''.
        '''</summary>
        Friend ReadOnly Property DELETE_DEPARA_DELETATIPOLOGRADOURO() As String
            Get
                Return ResourceManager.GetString("DELETE_DEPARA_DELETATIPOLOGRADOURO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE MARTE.VABR_TDE_PARA_GERAL 
        '''WHERE COD_PARAM_TAB = :COD_PARAM_TAB.
        '''</summary>
        Friend ReadOnly Property DELETE_DEPARA_SEGMENTO_SUB() As String
            Get
                Return ResourceManager.GetString("DELETE_DEPARA_SEGMENTO_SUB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM MARTE.COPR_TCLIENTE C
        '''WHERE C.COD_IDENTIFICACION_FISCAL = :IDFISCAL
        '''  AND C.FYH_CDATE &lt; (SELECT MAX(FYH_CDATE) FROM MARTE.COPR_TCLIENTE WHERE COD_IDENTIFICACION_FISCAL = :IDFISCAL) .
        '''</summary>
        Friend ReadOnly Property DELETE_MARTE_DELETACLIENTEDUPLICADO() As String
            Get
                Return ResourceManager.GetString("DELETE_MARTE_DELETACLIENTEDUPLICADO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE
        '''FROM MARTE.COPR_TDELEGACION d
        '''WHERE BOL_ACTIVO = 0 .
        '''</summary>
        Friend ReadOnly Property DELETE_MARTE_DELETADELEGACAO() As String
            Get
                Return ResourceManager.GetString("DELETE_MARTE_DELETADELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE
        '''FROM MARTE.COPR_TTIPO_CALLE
        '''WHERE DES_CORTA_TIPO_CALLE = :DES_CORTA_TIPO_CALLE
        '''  AND TO_NUMBER(COD_TIPO_CALLE) &gt; TO_NUMBER((SELECT MIN(COD_TIPO_CALLE) FROM MARTE.COPR_TTIPO_CALLE WHERE DES_CORTA_TIPO_CALLE = :DES_CORTA_TIPO_CALLE)).
        '''</summary>
        Friend ReadOnly Property DELETE_MARTE_DELETALOGRADOURODUPLICADO() As String
            Get
                Return ResourceManager.GetString("DELETE_MARTE_DELETALOGRADOURODUPLICADO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM MARTE.COPR_TSEGMENTO
        '''.
        '''</summary>
        Friend ReadOnly Property DELETE_MARTE_SEGMENTO() As String
            Get
                Return ResourceManager.GetString("DELETE_MARTE_SEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM MARTE.COPR_TSUBSEGMENTO
        '''.
        '''</summary>
        Friend ReadOnly Property DELETE_MARTE_SUBSEGMENTO() As String
            Get
                Return ResourceManager.GetString("DELETE_MARTE_SUBSEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --DELETA LIXO DA TABELA DO NOVI
        '''DELETE FROM ADA_XELEM X
        '''WHERE X.XELEM_COD_TABLA = &apos;59&apos;
        '''  AND X.XELEM_COD_IDIOMA = &apos;55&apos;
        '''  AND X.XELEM_COD_ATRIBUTO = 2
        '''  AND X.XELEM_COD_ELEMENTO NOT IN (SELECT A.COD_NOVI
        '''                                   FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
        '''                                   WHERE A.COD_PARAM_TAB = &apos;7&apos;).
        '''</summary>
        Friend ReadOnly Property DELETE_NOVI_CIDADESEMDEPARA() As String
            Get
                Return ResourceManager.GetString("DELETE_NOVI_CIDADESEMDEPARA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM DDLVIG.OCLTE O
        '''WHERE O.OCLTE_COD_NIF = :IDFISCAL
        '''  AND O.OCLTE_FEC_ALTA  &lt; (SELECT MAX(OCLTE_FEC_ALTA) FROM DDLVIG.OCLTE WHERE OCLTE_COD_NIF = :IDFISCAL).
        '''</summary>
        Friend ReadOnly Property DELETE_NOVI_DELETACLIENTEDUPLICADO() As String
            Get
                Return ResourceManager.GetString("DELETE_NOVI_DELETACLIENTEDUPLICADO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE
        '''FROM DDLVIG.OREGI .
        '''</summary>
        Friend ReadOnly Property DELETE_NOVI_DELETADELEGACAO() As String
            Get
                Return ResourceManager.GetString("DELETE_NOVI_DELETADELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE
        '''FROM DDLVIG.XELEM X
        '''WHERE X.XELEM_COD_TABLA = &apos;86&apos;.
        '''</summary>
        Friend ReadOnly Property DELETE_NOVI_DELETATIPOLOG() As String
            Get
                Return ResourceManager.GetString("DELETE_NOVI_DELETATIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE
        '''FROM DDLVIG.ODERE.
        '''</summary>
        Friend ReadOnly Property DELETE_NOVI_ODERE() As String
            Get
                Return ResourceManager.GetString("DELETE_NOVI_ODERE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM DBO.FAT_TCADCLI 
        '''WHERE CNP = :CNP
        '''  AND DATULTALT &lt; (SELECT MAX(DATULTALT) FROM DBO.FAT_TCADCLI WHERE CPF = :CNP).
        '''</summary>
        Friend ReadOnly Property DELETE_PROFAT_DELETACLIENTEDUPLICADO() As String
            Get
                Return ResourceManager.GetString("DELETE_PROFAT_DELETACLIENTEDUPLICADO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM DBO.FAT_TCADCLI 
        '''WHERE CPF = :CPF
        '''  AND DATULTALT &lt; (SELECT MAX(DATULTALT) FROM DBO.FAT_TCADCLI WHERE CPF = :CPF).
        '''</summary>
        Friend ReadOnly Property DELETE_PROFAT_DELETACLIENTEDUPLICADO_CPF() As String
            Get
                Return ResourceManager.GetString("DELETE_PROFAT_DELETACLIENTEDUPLICADO_CPF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE
        '''FROM FAT_TTABTIPLOG
        '''WHERE DESABRTIPLOG = :DESABRTIPLOG
        '''  AND TO_NUMBER(CODTIPLOG) &gt; TO_NUMBER((SELECT MIN(CODTIPLOG) FROM FAT_TTABTIPLOG WHERE DESABRTIPLOG = :DESABRTIPLOG)).
        '''</summary>
        Friend ReadOnly Property DELETE_PROFAT_DELETALOGRADOURODUPLICADO() As String
            Get
                Return ResourceManager.GetString("DELETE_PROFAT_DELETALOGRADOURODUPLICADO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --INSERE NOVOS ITENS AO DEPARA
        '''INSERT INTO MARTE.VABR_TDE_PARA_GERAL 
        '''VALUES 
        '''(:ID, &apos;7&apos;, :COD_MARTE, :COD_PROFAT, :COD_NOVI, SYSDATE, NULL).
        '''</summary>
        Friend ReadOnly Property INSERT_DEPARA_CIDADE() As String
            Get
                Return ResourceManager.GetString("INSERT_DEPARA_CIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO MARTE.VABR_TDE_PARA_GERAL
        '''VALUES
        '''(:OID_TABELA, &apos;5&apos;, :COD_MARTE, :COD_PROFAT, :COD_NOVI, SYSDATE, NULL).
        '''</summary>
        Friend ReadOnly Property INSERT_DEPARA_NORMALIZADELEGACAO() As String
            Get
                Return ResourceManager.GetString("INSERT_DEPARA_NORMALIZADELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO MARTE.VABR_TDE_PARA_GERAL
        '''VALUES
        '''(:OID_TABELA, &apos;6&apos;, :COD_MARTE, :COD_PROFAT, :COD_NOVI, SYSDATE, NULL).
        '''</summary>
        Friend ReadOnly Property INSERT_DEPARA_NORMALIZATIPOLOGRADOURO() As String
            Get
                Return ResourceManager.GetString("INSERT_DEPARA_NORMALIZATIPOLOGRADOURO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO MARTE.VABR_TDE_PARA_GERAL 
        '''VALUES
        '''(SYS_GUID(), :COD_PARAM_TAB, :COD_MARTE, :COD_PROFAT, NULL, SYSDATE, NULL).
        '''</summary>
        Friend ReadOnly Property INSERT_DEPARA_SEGMENTO_SUB() As String
            Get
                Return ResourceManager.GetString("INSERT_DEPARA_SEGMENTO_SUB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO COPR_TDELEGACION
        '''(OID_DELEGACION, COD_DELEGACION, DES_DELEGACION, DES_CORTA_DELEGACION, BOL_ACTIVO, OID_ZONAGERENCIAL, OID_PAIS, FYH_CDATE, DES_CUID)
        '''VALUES
        '''(:OID_DELEGACION, :COD_DELEGACION, :DES_DELEGACION, :DES_CORTA_DELEGACION, 1, &apos;CAC19C1C0E4D13A7E040007F01003FD5        &apos;, &apos;55                                      &apos;, SYSDATE(), &apos;OM13&apos;).
        '''</summary>
        Friend ReadOnly Property INSERT_MARTE_INSEREDELEGACAO() As String
            Get
                Return ResourceManager.GetString("INSERT_MARTE_INSEREDELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO MARTE.COPR_TFILIAL_COM_X_FAT FAT 
        ''' USING (SELECT &apos;PAR1&apos; COD_FILIAL_COMERCIAL
        '''              ,&apos;PAR2&apos; COD_EMPRESA_COMERCIAL
        '''              ,&apos;PAR3&apos; COD_FILIAL_FACTURACION
        '''        FROM dual) COD 
        ''' ON (COD.COD_FILIAL_COMERCIAL = FAT.COD_FILIAL_COMERCIAL 
        '''     AND COD.COD_EMPRESA_COMERCIAL = FAT.COD_EMPRESA_COMERCIAL
        '''     AND COD.COD_FILIAL_FACTURACION = FAT.COD_FILIAL_FACTURACION)
        ''' WHEN MATCHED THEN 
        '''      UPDATE SET FYH_MDATE = SYSDATE, DES_MUID = &apos;OM13&apos;
        ''' WHEN NOT MATCHED THEN 
        '''      INSERT  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property INSERT_MARTE_INSEREDEPARAFILIALFAT() As String
            Get
                Return ResourceManager.GetString("INSERT_MARTE_INSEREDEPARAFILIALFAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO MARTE.COPR_TCAD_FILIAL_FAT FAT 
        ''' USING (SELECT &apos;PAR1&apos; COD_FILIAL
        '''			  ,&apos;PAR2&apos; DES_FILIAL
        '''			  ,&apos;PAR3&apos; COD_CNPJ
        '''        FROM DUAL) COD 
        ''' ON (COD.COD_FILIAL = FAT.COD_FILIAL 
        '''     AND COD.DES_FILIAL = FAT.DES_FILIAL
        '''     AND COD.COD_CNPJ = FAT.COD_CNPJ)
        ''' WHEN MATCHED THEN 
        '''      UPDATE SET FYH_MDATE = SYSDATE, DES_MUID = &apos;OM13&apos;
        ''' WHEN NOT MATCHED THEN 
        '''      INSERT (COD_FILIAL, DES_FILIAL, COD_CNPJ, FYH_MDATE, DES_MUID)
        '''      VALUES (COD.COD_FILIAL, COD.DES_FILIAL, COD.COD_CNPJ, SYSDATE, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property INSERT_MARTE_INSEREESPELHOFILIALFAT() As String
            Get
                Return ResourceManager.GetString("INSERT_MARTE_INSEREESPELHOFILIALFAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO MARTE.COPR_TTIPO_CALLE
        '''VALUES
        '''(:OID_TIPO_CALLE, :COD_TIPO_CALLE, :DES_TIPO_CALLE, :DES_CORTA_TIPO_CALLE).
        '''</summary>
        Friend ReadOnly Property INSERT_MARTE_INSERETIPOLOG() As String
            Get
                Return ResourceManager.GetString("INSERT_MARTE_INSERETIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --INSERE CIDADE NOVI
        '''INSERT INTO ADA_XELEM
        '''VALUES
        '''(59,55,2,:COD_NOVI,:DES_MUN, &apos;OM13&apos;, TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;), TO_CHAR(SYSDATE, &apos;HH24MISS&apos;), &apos;00&apos;, :COD_COMERCIAL, NULL).
        '''</summary>
        Friend ReadOnly Property INSERT_NOVI_CIDADE() As String
            Get
                Return ResourceManager.GetString("INSERT_NOVI_CIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --INSERE NOVAS DIVISÕES NO NOVI
        '''INSERT INTO ADA_OTARI
        '''(ODIVI_COD_DIVI, ODIVI_NOC_DIVI, ODIVI_NOL_DIVI, ODIVI_USU_ULTACTU, ODIVI_FEC_ULTACTU, ODIVI_HOR_ULTACTU, ODIVI_COD_OPERATIV, ODIVI_COD_ERP, COD_COMERCIAL)
        '''VALUES 
        '''(:ODIVI_COD_DIVI, :ODIVI_NOC_DIVI, :ODIVI_NOL_DIVI, &apos;OM13&apos;, TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;), TO_CHAR(SYSDATE, &apos;HH24MISS&apos;), &apos;VI&apos;, NULL, :COD_COMERCIAL).
        '''</summary>
        Friend ReadOnly Property INSERT_NOVI_DIVISAO() As String
            Get
                Return ResourceManager.GetString("INSERT_NOVI_DIVISAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO DDLVIG.OREGI
        '''VALUES 
        '''(:OREGI_COD_REG, :OREGI_NOC_REG, :OREGI_NOL_REG, &apos;OM13&apos;, TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;), TO_CHAR(SYSDATE, &apos;HH24MISS&apos;)).
        '''</summary>
        Friend ReadOnly Property INSERT_NOVI_INSEREDELEGACAO() As String
            Get
                Return ResourceManager.GetString("INSERT_NOVI_INSEREDELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO DDLVIG.XELEM
        '''VALUES 
        '''(86, 55, 2, :XELEM_COD_ELEMENTO, :XELEM_VAL_ATRIBUTO, &apos;OM13&apos;, TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;), TO_CHAR(SYSDATE, &apos;HH24MISS&apos;), &apos;00&apos;, :COD_COMERCIAL, NULL).
        '''</summary>
        Friend ReadOnly Property INSERT_NOVI_INSERETIPOLOG() As String
            Get
                Return ResourceManager.GetString("INSERT_NOVI_INSERETIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO DDLVIG.ODERE
        '''SELECT DISTINCT &apos;OM13&apos; ODERE_USU_ULTACTU , TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;) ODERE_FEC_ULTACTU , 
        '''       TO_CHAR(SYSDATE, &apos;HH24MISS&apos;) ODERE_HOR_ULTACTU, REG.OREGI_COD_REG ODERE_COD_REG , V.COD_NOVI ODERE_COD_DELEG 
        '''FROM MARTE.COPR_TFILIAL F INNER JOIN MARTE.COPR_TDELEGACION D ON F.OID_DELEGACION = D.OID_DELEGACION
        '''  INNER JOIN ADA_OREGI REG ON D.COD_DELEGACION = REG.OREGI_COD_REG
        '''  INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON F.COD_FILIAL = V.COD_MARTE
        '''  INNER JOIN DDLVIG.ODELE O ON O [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property INSERT_NOVI_ODERE() As String
            Get
                Return ResourceManager.GetString("INSERT_NOVI_ODERE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO FAT_TTABTIPLOG
        '''VALUES (:CODTIPLOG, :DESTIPLOG, :DESABRTIPLOG, 1, 1, GETDATE(), 1).
        '''</summary>
        Friend ReadOnly Property INSERT_PROFAT_INSERETIPOLOG() As String
            Get
                Return ResourceManager.GetString("INSERT_PROFAT_INSERETIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO dbo.FAT_TCADFUNPAT PAT1
        ''' USING (SELECT &apos;PAR1&apos; CODFUNPAT, &apos;PAR2&apos; DESFUNPAT, &apos;PAR3&apos; CODFUNPATCOM) PAT2 
        ''' ON (PAT1.CODFUNPAT = PAT2.CODFUNPAT)
        ''' WHEN MATCHED THEN 
        '''      UPDATE SET DATULTALT = GETDATE(), CODUSU = 1, DESFUNPAT = PAT2.DESFUNPAT, CODFUNPATCOM = PAT2.CODFUNPATCOM
        ''' WHEN NOT MATCHED THEN 
        '''      INSERT (CODFUNPAT, DESFUNPAT, CODUSU, DATULTALT, CODFUNPATCOM)
        '''      VALUES (PAT2.CODFUNPAT, PAT2.DESFUNPAT, 1, GETDATE(), PAT2.CODFUNPATCOM);.
        '''</summary>
        Friend ReadOnly Property INSERT_PROFAT_MERGETIPOPOSTO() As String
            Get
                Return ResourceManager.GetString("INSERT_PROFAT_MERGETIPOPOSTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO MARTE.COPR_TSEGMENTO SEG1
        '''USING (SELECT &apos;0&apos; OID_SEGMENTO FROM DUAL) SEG2 
        '''ON (SEG1.OID_SEGMENTO = SEG2.OID_SEGMENTO)
        '''WHEN NOT MATCHED THEN 
        '''INSERT (OID_SEGMENTO, COD_SEGMENTO, DES_SEGMENTO, BOL_ACTIVO, FYH_CDATE, DES_CUID)
        '''VALUES (&apos;0&apos;, &apos;0&apos;, &apos;SEGMENTO NÃO INFORMADO/CLASSIFICADO&apos;, 1,	SYSDATE, &apos;OM13&apos;)
        '''.
        '''</summary>
        Friend ReadOnly Property INSERT_SEGMENTO_MARTE() As String
            Get
                Return ResourceManager.GetString("INSERT_SEGMENTO_MARTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO MARTE.COPR_TSUBSEGMENTO SSEG1
        '''USING (SELECT &apos;0&apos; OID_SUBSEGMENTO FROM DUAL) SSEG2 
        '''ON (SSEG1.OID_SUBSEGMENTO = SSEG2.OID_SUBSEGMENTO)
        '''WHEN NOT MATCHED THEN 
        '''INSERT (OID_SUBSEGMENTO, OID_SEGMENTO, COD_SUBSEGMENTO, DES_SUBSEGMENTO, BOL_ACTIVO)
        '''VALUES (&apos;0&apos;,&apos;0&apos;, &apos;0&apos;, &apos;SUBSEGMENTO NÃO INFORMADO/CLASSIFICADO&apos;, 1)
        '''.
        '''</summary>
        Friend ReadOnly Property INSERT_SUBSEGMENTO_MARTE() As String
            Get
                Return ResourceManager.GetString("INSERT_SUBSEGMENTO_MARTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO MARTE.COPR_TSEGMENTO SEG1
        ''' USING (SELECT &apos;PAR1&apos; COD_SEGMENTO, &apos;PAR2&apos; DES_SEGMENTO , &apos;PAR3&apos; COD_SEGMENTO_PROFAT, &apos;PAR4&apos; OID_SEGMENTO FROM DUAL) SEG2 
        ''' ON (SEG1.OID_SEGMENTO = SEG2.OID_SEGMENTO)
        ''' WHEN MATCHED THEN 
        '''      UPDATE SET COD_SEGMENTO = SEG2.COD_SEGMENTO_PROFAT, 
        '''                 DES_SEGMENTO  = SEG2.DES_SEGMENTO, 
        '''                 BOL_ACTIVO = 1
        ''' WHEN NOT MATCHED THEN 
        '''      INSERT (OID_SEGMENTO, COD_SEGMENTO, DES_SEGMENTO, BOL_ACTIVO, FYH_CDATE, DES_CUID)
        '''      VALUES (&apos;PAR5&apos;,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MERGE_MARTE_SEGMENTO() As String
            Get
                Return ResourceManager.GetString("MERGE_MARTE_SEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MERGE INTO MARTE.COPR_TSUBSEGMENTO SEG1
        ''' USING (SELECT &apos;PAR1&apos; COD_SUBSEGMENTO, &apos;PAR2&apos; DES_SUBSEGMENTO, &apos;PAR3&apos; COD_SUBSEGMENTO_PROFAT, &apos;PAR4&apos; OID_SEGMENTO, &apos;PAR5&apos; OID_SUBSEGMENTO FROM DUAL) SEG2 
        ''' ON (SEG1.OID_SUBSEGMENTO = SEG2.OID_SUBSEGMENTO)
        ''' WHEN MATCHED THEN 
        '''      UPDATE SET COD_SUBSEGMENTO  = SEG2.COD_SUBSEGMENTO_PROFAT, 
        '''                 DES_SUBSEGMENTO   = SEG2.DES_SUBSEGMENTO, 
        '''                 BOL_ACTIVO  = 1
        ''' WHEN NOT MATCHED THEN 
        '''      INSERT (OID_SUBSEGMENTO, OID_SEGMENTO, COD_SUBSEGM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MERGE_MARTE_SUBSEGMENTO() As String
            Get
                Return ResourceManager.GetString("MERGE_MARTE_SUBSEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT A.COD_MARTE, A.COD_PROFAT, S.OID_SEGMENTO
        '''FROM MARTE.VABR_TDE_PARA_GERAL A INNER JOIN MARTE.COPR_TSEGMENTO S ON A.COD_MARTE = S.COD_SEGMENTO
        '''WHERE A.COD_PARAM_TAB = &apos;1&apos;
        '''  {0}.
        '''</summary>
        Friend ReadOnly Property SELECT_DEPARA_SEGMENTO() As String
            Get
                Return ResourceManager.GetString("SELECT_DEPARA_SEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT A.COD_MARTE OID_SUBSEGMENTO, A.COD_PROFAT, S.COD_SUBSEGMENTO, S.OID_SEGMENTO
        '''FROM MARTE.VABR_TDE_PARA_GERAL A INNER JOIN MARTE.COPR_TSUBSEGMENTO S ON A.COD_MARTE = S.OID_SUBSEGMENTO
        '''WHERE A.COD_PARAM_TAB = &apos;2&apos;
        '''{0}.
        '''</summary>
        Friend ReadOnly Property SELECT_DEPARA_SUBSEGMENTO() As String
            Get
                Return ResourceManager.GetString("SELECT_DEPARA_SUBSEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DISTINCT F.COD_FILIAL COMERCIAL, O.ODELE_COD_DELEG NOVI      
        '''FROM MARTE.COPR_TFILIAL F
        '''INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON F.COD_FILIAL = V.COD_MARTE
        '''INNER JOIN DDLVIG.ODELE O ON O.ODELE_COD_DELEG = V.COD_NOVI
        '''WHERE V.COD_PARAM_TAB IN(&apos;4&apos;,&apos;13&apos;)
        '''ORDER BY F.COD_FILIAL.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_BUSCARFILIAIS() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_BUSCARFILIAIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CL.COD_TIPO_CALLE
        '''       ,CL.DES_TIPO_CALLE
        '''       ,CL.DES_CORTA_TIPO_CALLE
        '''       ,V.COD_NOVI
        '''       ,V.COD_PROFAT
        '''FROM MARTE.COPR_TTIPO_CALLE CL
        '''INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON CL.COD_TIPO_CALLE = V.COD_MARTE
        '''WHERE V.COD_PARAM_TAB = &apos;6&apos;
        '''ORDER BY V.COD_PROFAT.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_BUSCARTIPOLOG() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_BUSCARTIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --BUSCA CIDADE NO MARTE QUE NÃO ESTÃO NO DEPARA
        '''SELECT C.OID_ESTADO, C.COD_CIUDAD, C.DES_CIUDAD
        '''FROM MARTE.COPR_TCIUDAD C
        '''WHERE C.COD_CIUDAD NOT IN (SELECT A.COD_MARTE
        '''							FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
        '''							WHERE A.COD_PARAM_TAB = &apos;7&apos;).
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_CIDADESEMDEPARA() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_CIDADESEMDEPARA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT COUNT(1) QTD
        '''FROM MARTE.COPR_TTIPO_CALLE CL.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_COUNTTIPOLOG() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_COUNTTIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --BUSCA DADOS PARA NORMALIZAÇÃO
        '''SELECT A.COD_MARTE, A.COD_PROFAT, A.COD_NOVI
        '''FROM MARTE.COPR_TCIUDAD C INNER JOIN MARTE.VABR_TDE_PARA_GERAL A ON C.COD_CIUDAD = A.COD_MARTE
        '''WHERE A.COD_PARAM_TAB = &apos;7&apos;
        '''ORDER BY A.COD_PROFAT DESC.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_DADOSCIDADE() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_DADOSCIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --BUSCA INFORMAÇÕES CLIENTE MARTE
        '''SELECT C.COD_CLIENTE
        '''       ,V.COD_NOVI
        '''       ,V.COD_PROFAT
        '''       ,C.OID_TIPO_ID_FISCAL
        '''       ,C.COD_IDENTIFICACION_FISCAL
        '''       ,C.DES_NOMBRE_FANTASIA
        '''       ,C.DES_RAZON_SOCIAL
        '''       ,C.FEC_INICIO
        '''       ,C.FEC_FIN
        '''       ,D.COD_CEP
        '''       ,D.DES_CALLE
        '''       ,D.NUM_NRO
        '''       ,D.DES_COMPL_DIRECCION
        '''       ,L.COD_TIPO_CALLE
        '''       ,L.DES_TIPO_CALLE
        '''       ,D.DES_BARRIO
        '''       ,CI.DES_CIUDAD
        '''	   ,TRIM(CI.OID_ESTADO) as ESTADO
        '''       ,C.BOL_ACTIVO
        '''F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_DADOSCLIENTE() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_DADOSCLIENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --OBTEM DADOS DO MARTE
        '''SELECT COD_MARTE, COD_PROFAT, COD_NOVI, OTARI_COD_COMPO, COD_COMERCIAL 
        '''FROM MARTE.VABR_TDE_PARA_GERAL 
        '''     INNER JOIN DDLVIG.OTARI ON VABR_TDE_PARA_GERAL.COD_NOVI = OTARI.OTARI_COD_COMPO
        '''     INNER JOIN MARTE.COPR_TPRODUCTO ON VABR_TDE_PARA_GERAL.COD_MARTE = COPR_TPRODUCTO.COD_PRODUCTO
        '''WHERE COD_PARAM_TAB = 9
        '''ORDER BY COD_MARTE
        '''.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_DADOSDIVISAO() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_DADOSDIVISAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''    (SELECT DES_VALOR
        '''     FROM
        '''         MARTE.COPR_TVALOR_ATRIBUTOXSUBCLI_CO
        '''         INNER JOIN MARTE.GEPR_TATRIBUTO
        '''                ON  COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_ATRIBUTO = GEPR_TATRIBUTO.OID_ATRIBUTO
        '''         INNER JOIN MARTE.COPR_TPARAMETRO
        '''                ON  GEPR_TATRIBUTO.COD_ATRIBUTO = COPR_TPARAMETRO.VALOR
        '''     WHERE
        '''         COPR_TPARAMETRO.COD_PARAMETRO = &apos;ATBC_EMAIL_SUB&apos;
        '''     AND COPR_TVALOR_ATRIBUTOXSUBCLI_CO.OID_SUBCLIENTE = COPR_TSUBCLIENTE.OID_SUBCLIENTE) AS EmailR [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_DADOSRESPFAT() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_DADOSRESPFAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT S.COD_SUBCLIENTE COD_SUB_MARTE
        '''	   ,S.OID_CLIENTE
        '''       ,O.OSBCL_COD_CLIENTE COD_CLI_NOVI
        '''       ,O.OSBCL_COD_SUBCLI COD_SUB_NOVI
        '''       ,V.COD_PROFAT
        '''       ,S.OID_TIPO_ID_FISCAL
        '''       ,S.COD_IDENTIFICACION_FISCAL
        '''       ,S.DES_SUBCLIENTE
        '''       ,S.DES_CORTA_SUBCLIENTE
        '''       ,S.COD_INSCRIPCION_ESTATAL
        '''       ,S.COD_INSCRIPCION_MUNICIPAL
        '''       ,D.COD_CEP
        '''       ,D.DES_CALLE
        '''       ,D.NUM_NRO
        '''       ,D.DES_COMPL_DIRECCION
        '''       ,L.COD_TIPO_CALLE
        '''       ,L.DES_TIPO_CALLE
        '''       ,D [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_DADOSSUBCLIENTE() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_DADOSSUBCLIENTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT P.COD_TIPO_PUESTO COD_COMERCIAL, P.DES_TIPO_PUESTO, V.COD_NOVI
        '''FROM MARTE.COPR_TTIPO_PUESTO P
        '''INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON P.COD_TIPO_PUESTO = V.COD_MARTE
        '''INNER JOIN DDLVIG.XELEM X ON X.XELEM_COD_ELEMENTO =  V.COD_NOVI
        '''WHERE V.COD_PARAM_TAB = &apos;8&apos;
        '''  AND X.XELEM_COD_TABLA = &apos;73&apos;
        '''  AND X.XELEM_COD_IDIOMA = &apos;55&apos;
        '''  AND XELEM_COD_ATRIBUTO = 2
        '''  --AND P.BOL_ACTIVO = 1
        '''ORDER BY 1.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_DADOSTIPOPOSTO() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_DADOSTIPOPOSTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT S.OID_SEGMENTO, S.COD_SEGMENTO, S.DES_SEGMENTO,
        '''       SUB.OID_SUBSEGMENTO, SUB.COD_SUBSEGMENTO, SUB.DES_SUBSEGMENTO
        '''FROM MARTE.COPR_TSEGMENTO S 
        '''     INNER JOIN MARTE.COPR_TSUBSEGMENTO SUB ON S.OID_SEGMENTO = SUB.OID_SEGMENTO
        '''WHERE 0=0
        '''  {0}.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_SEGSUBSEG() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_SEGSUBSEG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select max(to_number(COD_TIPO_CALLE)) +1 cod
        '''FROM MARTE.COPR_TTIPO_CALLE.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_ULTIMOCODIGOLOGRADOURO() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_ULTIMOCODIGOLOGRADOURO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT C.COD_IDENTIFICACION_FISCAL, C.COD_CLIENTE, C.DES_RAZON_SOCIAL, COUNT(C.COD_IDENTIFICACION_FISCAL) QTD
        '''FROM MARTE.COPR_TCLIENTE C INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON C.COD_CLIENTE = V.COD_MARTE     
        '''WHERE C.BOL_POTENCIAL = 0    
        '''  AND V.COD_PARAM_TAB = &apos;10&apos;
        '''GROUP BY C.COD_IDENTIFICACION_FISCAL, C.COD_CLIENTE, C.DES_RAZON_SOCIAL
        '''HAVING COUNT(C.COD_IDENTIFICACION_FISCAL) &gt; 1  .
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_VERIFICADUPLICIDADE() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_VERIFICADUPLICIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CL.DES_CORTA_TIPO_CALLE
        '''FROM MARTE.COPR_TTIPO_CALLE CL
        '''HAVING COUNT(CL.DES_CORTA_TIPO_CALLE) &gt; 1
        '''GROUP BY CL.DES_CORTA_TIPO_CALLE.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_VERIFICADUPLICIDADETIPOLOGRADOURO() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_VERIFICADUPLICIDADETIPOLOGRADOURO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --VERIFICA NIF NULO
        '''SELECT C.COD_CLIENTE, S.COD_SUBCLIENTE, C.COD_IDENTIFICACION_FISCAL NIF_CLIENTE, S.COD_IDENTIFICACION_FISCAL NIF_SUBCLIENTE
        '''FROM MARTE.COPR_TCLIENTE C INNER JOIN MARTE.COPR_TSUBCLIENTE S ON C.OID_CLIENTE = S.OID_CLIENTE
        '''     INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON V.COD_MARTE = S.OID_SUBCLIENTE
        '''WHERE V.COD_PARAM_TAB = &apos;11&apos;
        '''  AND S.BOL_ES_PTO_FACTURACION = 1
        '''  AND S.COD_IDENTIFICACION_FISCAL IS NULL
        '''ORDER BY 1, 2 .
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_VERIFICANIFNULO() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_VERIFICANIFNULO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --VERIFICA NIF DUPLICADO
        '''SELECT COUNT(S.COD_IDENTIFICACION_FISCAL) QTD, S.COD_IDENTIFICACION_FISCAL
        '''FROM MARTE.COPR_TSUBCLIENTE S INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON V.COD_MARTE = S.OID_SUBCLIENTE
        '''WHERE V.COD_PARAM_TAB = &apos;11&apos;
        '''  AND S.BOL_ES_PTO_FACTURACION = 1
        '''GROUP BY S.COD_IDENTIFICACION_FISCAL
        '''HAVING COUNT(S.COD_IDENTIFICACION_FISCAL) &gt; 1.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_VERIFICANIFSUPLICADO() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_VERIFICANIFSUPLICADO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --VERIFICA RAZÃO DIFERENTE DE CLIENTE
        '''SELECT C.COD_CLIENTE, S.COD_SUBCLIENTE, C.COD_IDENTIFICACION_FISCAL NIF_CLIENTE, S.COD_IDENTIFICACION_FISCAL NIF_SUBCLIENTE
        '''FROM MARTE.COPR_TCLIENTE C INNER JOIN MARTE.COPR_TSUBCLIENTE S ON C.OID_CLIENTE = S.OID_CLIENTE
        '''     INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON V.COD_MARTE = S.OID_SUBCLIENTE
        '''WHERE V.COD_PARAM_TAB = &apos;11&apos;
        '''  AND SUBSTR(C.COD_IDENTIFICACION_FISCAL, 1, 8) &lt;&gt; SUBSTR(S.COD_IDENTIFICACION_FISCAL, 1, 8)
        '''  AND S.BOL_ES_PTO_FACTURACION = 1
        '''ORDER BY C.C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SELECT_MARTE_VERIFICARAZAONIF() As String
            Get
                Return ResourceManager.GetString("SELECT_MARTE_VERIFICARAZAONIF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT XELEM_COD_ELEMENTO
        '''FROM ADA_XELEM 
        '''WHERE COD_COMERCIAL    = :COD_COMERCIAL
        '''AND XELEM_COD_TABLA    = &apos;86&apos;
        '''AND XELEM_COD_IDIOMA   = &apos;55&apos;
        '''AND XELEM_COD_ATRIBUTO = &apos;2&apos;.
        '''</summary>
        Friend ReadOnly Property SELECT_NOVI_BUSCACODVIA() As String
            Get
                Return ResourceManager.GetString("SELECT_NOVI_BUSCACODVIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT C.OCLTE_COD_NIF, COUNT(C.OCLTE_COD_NIF) QTD
        '''FROM DDLVIG.OCLTE C                                                 
        '''GROUP BY C.OCLTE_COD_NIF
        '''HAVING COUNT(C.OCLTE_COD_NIF) &gt; 1 .
        '''</summary>
        Friend ReadOnly Property SELECT_NOVI_VERIFICADUPLICIDADE() As String
            Get
                Return ResourceManager.GetString("SELECT_NOVI_VERIFICADUPLICIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT C.COD_CLIENTE, C.DES_RAZON_SOCIAL, COD_IDENTIFICACION_FISCAL
        '''FROM MARTE.COPR_TCLIENTE C INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON C.COD_CLIENTE = V.COD_MARTE     
        '''WHERE C.BOL_POTENCIAL = 0    
        '''  AND V.COD_PARAM_TAB = &apos;10&apos;
        '''  AND C.COD_IDENTIFICACION_FISCAL IS NULL.
        '''</summary>
        Friend ReadOnly Property SELECT_NOVI_VERIFICAFISCALNULO() As String
            Get
                Return ResourceManager.GetString("SELECT_NOVI_VERIFICAFISCALNULO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT V.COD_PARAM_TAB, V.COD_PROFAT
        '''FROM MARTE.VABR_TDE_PARA_GERAL V
        '''WHERE V.COD_PARAM_TAB IN(&apos;4&apos;,&apos;13&apos;)
        '''  AND V.COD_MARTE = :COD_COMERCIAL
        '''ORDER BY TO_NUMBER(V.COD_MARTE).
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_BUSCACODFILIAL() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_BUSCACODFILIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CODFIL, NOMFIL, CNP, CODEMP
        '''FROM FAT_TCADFIL
        '''where CODEMP IN (1,2)
        '''  AND CODFIL = @CODFIL
        '''ORDER BY 1.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_BUSCAFILIAL() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_BUSCAFILIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CODREG, DESREG, CODUF, DESABRREG
        '''FROM FAT_TTABREG.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_BUSCARDELEGACAO() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_BUSCARDELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CODFIL, NOMFIL, CNP, CODEMP
        '''FROM FAT_TCADFIL
        '''WHERE CODEMP IN (1,2)
        '''ORDER BY 1.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_BUSCARFILIAIS() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_BUSCARFILIAIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *
        '''FROM FAT_TTABTIPLOG
        '''{0}.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_BUSCARTIPOLOG() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_BUSCARTIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT COUNT(1) QTD
        '''FROM FAT_TTABTIPLOG.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_COUNTTIPOLOG() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_COUNTTIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --BUSCA DADOS DO PROFAT 
        '''SELECT CODMUN, NOMMUN, CODUF, CODIBGE
        '''FROM FAT_TTABMUN 
        '''WHERE {0} --CODMUN = @CODMUN/NOMMUN = @NOMMUN.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_DADOSCIDADE() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_DADOSCIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --RECUPERA DADOS DO PROFAT DE TIPO DE SERVIÇO E FAMILIA DE SERVIÇO
        '''SELECT TIPSER.CODTIPSER, TIPSER.DESSER , CODITECOB, CODSEGCOM, FAM.CODFAM, FAM.DESFAM
        '''FROM FAT_TCADTIPSER AS TIPSER WITH(NOLOCK) 
        '''       INNER JOIN FAT_TCADSUBSEG AS SUBSEG WITH(NOLOCK) ON TIPSER.CODSUBSEG = SUBSEG.CODSUBSEG 
        '''       INNER JOIN FAT_TCADSEG AS SEG WITH(NOLOCK) ON SUBSEG.CODSEG = SEG.CODSEG 
        '''												 AND SEG.CODDIV = 2 
        '''       INNER JOIN DBO.FAT_TTABFAM AS FAM WITH(NOLOCK) ON FAM.CODSEG = SUBSEG.CODSEG 
        '''       INNER  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_DADOSDIVISAO() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_DADOSDIVISAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT S.CODRAMATV, S.DESRAMATV, SUB.CODSUBRAMATV, SUB.DESSUBRAMATV
        '''FROM FAT_TTABRELRAMATV AS J WITH(NOLOCK) 
        '''	 INNER JOIN FAT_TTABRAMATV AS S WITH(NOLOCK) ON J.CODRAMATV = S.CODRAMATV
        '''	 INNER JOIN FAT_TTABSUBRAMATV AS SUB WITH(NOLOCK) ON J.CODSUBRAMATV = SUB.CODSUBRAMATV
        '''ORDER BY J.CODRAMATV, J.CODSUBRAMATV.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_DADOSSEG_SUB() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_DADOSSEG_SUB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CODRAMATV, DESRAMATV
        '''FROM FAT_TTABRAMATV WITH(NOLOCK) 
        '''WHERE CODRAMATV =  @CODRAMATV.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_SEGMENTO() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_SEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CODSUBRAMATV, DESSUBRAMATV
        '''FROM FAT_TTABSUBRAMATV WITH(NOLOCK)
        '''WHERE CODSUBRAMATV = @CODSUBRAMATV.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_SUBSEGMENTO() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_SUBSEGMENTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT MAX(CODTIPLOG) + 1 cod FROM FAT_TTABTIPLOG.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_ULTIMOCODIGOLOGRADOURO() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_ULTIMOCODIGOLOGRADOURO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CNP, COUNT(CNP) QTD
        '''FROM DBO.FAT_TCADCLI 
        '''GROUP BY CNP
        '''HAVING COUNT(CNP) &gt; 1.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_VERIFICADUPLICIDADE() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_VERIFICADUPLICIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CPF, COUNT(CPF) QTD
        '''FROM DBO.FAT_TCADCLI 
        '''GROUP BY CPF
        '''HAVING COUNT(CPF) &gt; 1.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_VERIFICADUPLICIDADE_CPF() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_VERIFICADUPLICIDADE_CPF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DESABRTIPLOG
        '''FROM FAT_TTABTIPLOG
        '''GROUP BY DESABRTIPLOG
        '''HAVING COUNT(DESABRTIPLOG) &gt;1.
        '''</summary>
        Friend ReadOnly Property SELECT_PROFAT_VERIFICADUPLICIDADETIPOLOGRADOURO() As String
            Get
                Return ResourceManager.GetString("SELECT_PROFAT_VERIFICADUPLICIDADETIPOLOGRADOURO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE MARTE.COPR_TCLIENTE
        '''   SET OID_SEGMENTO = &apos;0&apos;, OID_SUBSEGMENTO = &apos;0&apos;
        '''.
        '''</summary>
        Friend ReadOnly Property UPDATE_CLIENTE_MARTE() As String
            Get
                Return ResourceManager.GetString("UPDATE_CLIENTE_MARTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA COD IBGE NO MARTE
        '''UPDATE MARTE.COPR_TCIUDAD
        '''   SET COD_IBGE = :COD_IBGE,
        '''	   FYH_MDATE = SYSDATE,
        '''	   DES_MUID = &apos;OM13&apos;
        '''WHERE COD_CIUDAD = :COD_CIUDAD	  .
        '''</summary>
        Friend ReadOnly Property UPDATE_MARTE_ATUALIZACIDADE() As String
            Get
                Return ResourceManager.GetString("UPDATE_MARTE_ATUALIZACIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE COPR_TDELEGACION
        '''SET COD_DELEGACION = :COD_PROFAT,
        '''	DES_DELEGACION = :DES_PROFAT
        '''WHERE DES_CORTA_DELEGACION = :UF_PROFAT
        '''  AND BOL_ACTIVO = 1.
        '''</summary>
        Friend ReadOnly Property UPDATE_MARTE_ATUALIZACODDELEGACAO() As String
            Get
                Return ResourceManager.GetString("UPDATE_MARTE_ATUALIZACODDELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE COPR_TDELEGACION
        '''SET COD_DELEGACION = :COD_PROVISORIO
        '''WHERE COD_DELEGACION = :COD_PROFAT.
        '''</summary>
        Friend ReadOnly Property UPDATE_MARTE_ATUALIZACODDELEGACAO_AJUSTE() As String
            Get
                Return ResourceManager.GetString("UPDATE_MARTE_ATUALIZACODDELEGACAO_AJUSTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE MARTE.COPR_TTIPO_CALLE 
        '''   SET COD_TIPO_CALLE = :COD_PROFAT
        '''WHERE  COD_TIPO_CALLE = :COD_MARTE.
        '''</summary>
        Friend ReadOnly Property UPDATE_MARTE_TIPOLOG() As String
            Get
                Return ResourceManager.GetString("UPDATE_MARTE_TIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE MARTE.COPR_TTIPO_CALLE 
        '''   SET COD_TIPO_CALLE = COD_TIPO_CALLE || &apos;_&apos;
        '''WHERE  COD_TIPO_CALLE IN (SELECT COD_MARTE FROM MARTE.VABR_TDE_PARA_GERAL V WHERE V.COD_PARAM_TAB = &apos;6&apos;).
        '''</summary>
        Friend ReadOnly Property UPDATE_MARTE_TIPOLOGTEMP() As String
            Get
                Return ResourceManager.GetString("UPDATE_MARTE_TIPOLOGTEMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --ATUALIZA COD IBGE NO NOVI
        '''--UPDATE ADA_XELEM
        '''UPDATE XELEM
        '''   SET COD_COMERCIAL = :COD_IBGE
        '''WHERE XELEM_COD_TABLA = &apos;59&apos;
        '''  AND XELEM_COD_IDIOMA = &apos;55&apos;
        '''  AND XELEM_COD_ELEMENTO = :COD_CIUDAD	
        '''  AND XELEM_COD_ATRIBUTO = 2
        '''  AND XELEM_COD_DELEGA = &apos;00&apos;.
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_ATUALIZACIDADE() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_ATUALIZACIDADE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE DDLVIG.ODELE
        '''SET COD_FILIAL_COMERCIAL = :COD_COMERCIAL,
        '''	ODELE_USU_ULTACTU = &apos;OM13&apos;,
        '''	ODELE_FEC_ULTACTU = TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;),
        '''	ODELE_HOR_ULTACTU = TO_CHAR(SYSDATE, &apos;HH24MISS&apos;)
        '''WHERE ODELE_COD_DELEG = :COD_NOVI.
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_ATUALIZACODCOMERCIAL() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_ATUALIZACODCOMERCIAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE ADA_XELEM
        '''   SET COD_COMERCIAL = :COD_COMERCIAL,
        '''       XELEM_USU_ULTACTU = &apos;OM13&apos;,
        '''       XELEM_FEC_ULTACTU = TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;),
        '''       XELEM_HOR_ULTACTU = TO_CHAR(SYSDATE, &apos;HH24MISS&apos;)
        '''WHERE XELEM_COD_TABLA = &apos;73&apos;
        '''  AND XELEM_COD_IDIOMA = 55
        '''  AND XELEM_COD_ATRIBUTO IN (2,3,4)
        '''  AND XELEM_COD_ELEMENTO = :COD_NOVI.
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_ATUALIZACODCOMERCIAL1() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_ATUALIZACODCOMERCIAL1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE DDLVIG.OREGI
        '''SET OREGI_COD_REG = :COD_PROFAT
        '''WHERE TRIM(OREGI_NOC_REG) = :UF_PROFAT
        '''  AND (TRIM(OREGI_NOL_REG) = :DES_PROFAT OR TRIM(OREGI_NOL_REG) = :DES_PROFAT2).
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_ATUALIZACODDELEGACAO() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_ATUALIZACODDELEGACAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE DDLVIG.OREGI
        '''SET OREGI_COD_REG = :COD_PROVISORIO
        '''WHERE TRIM(OREGI_COD_REG) = :COD_PROFAT.
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_ATUALIZACODDELEGACAO_AJUSTE() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_ATUALIZACODDELEGACAO_AJUSTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE DDLVIG.ODERE
        '''SET ODERE_COD_REG = :COD_PROFAT,
        '''	ODERE_USU_ULTACTU = &apos;OM13&apos;,
        '''	ODERE_FEC_ULTACTU = TO_CHAR(SYSDATE, &apos;YYYYMMDD&apos;), 
        '''	ODERE_HOR_ULTACTU = TO_CHAR(SYSDATE, &apos;HH24MISS&apos;)
        '''WHERE TRIM(ODERE_COD_REG) = (SELECT TRIM(OREGI_COD_REG) FROM DDLVIG.OREGI WHERE TRIM(OREGI_NOC_REG) = :UF_PROFAT AND (TRIM(OREGI_NOL_REG) = :DES_PROFAT OR TRIM(OREGI_NOL_REG) = :DES_PROFAT2)).
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_ATUALIZACODDELEGACAO_REFERENCIA() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_ATUALIZACODDELEGACAO_REFERENCIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE DDLVIG.XELEM
        '''   SET COD_COMERCIAL = :CODCOMERCIAL
        '''WHERE XELEM_COD_ELEMENTO = :COD_ELEMENTO  
        '''  AND XELEM_COD_TABLA    = &apos;86&apos;
        '''  AND XELEM_COD_IDIOMA   = &apos;55&apos;
        '''  AND XELEM_COD_ATRIBUTO = &apos;2&apos;.
        '''</summary>
        Friend ReadOnly Property UPDATE_NOVI_TIPOLOG() As String
            Get
                Return ResourceManager.GetString("UPDATE_NOVI_TIPOLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE FAT_TTABTIPLOG
        '''   SET CODTIPLOGCOM = @CODCOMERCIAL
        '''WHERE CODTIPLOG = @COD_PROFAT  .
        '''</summary>
        Friend ReadOnly Property UPDATE_PROFAT_TIPOLOG() As String
            Get
                Return ResourceManager.GetString("UPDATE_PROFAT_TIPOLOG", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
