'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSPROFAT
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ClienteMarteProfatSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClienteMarteProfat
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AtualizarDadosClienteVAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaCnpjCpfClienteSubClienteVAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AtualizarDadosSubClienteVAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Prosegur.OM13.Migracao.My.MySettings.Default.Prosegur_OM13_Migracao_WSPROFAT_ClienteMarteProfat
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AtualizarDadosClienteVACompleted As AtualizarDadosClienteVACompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaCnpjCpfClienteSubClienteVACompleted As ConsultaCnpjCpfClienteSubClienteVACompletedEventHandler
        
        '''<remarks/>
        Public Event AtualizarDadosSubClienteVACompleted As AtualizarDadosSubClienteVACompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtualizarDadosClienteVA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AtualizarDadosClienteVA(ByVal oDados As DadosWsCliente) As Retorno
            Dim results() As Object = Me.Invoke("AtualizarDadosClienteVA", New Object() {oDados})
            Return CType(results(0),Retorno)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AtualizarDadosClienteVAAsync(ByVal oDados As DadosWsCliente)
            Me.AtualizarDadosClienteVAAsync(oDados, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AtualizarDadosClienteVAAsync(ByVal oDados As DadosWsCliente, ByVal userState As Object)
            If (Me.AtualizarDadosClienteVAOperationCompleted Is Nothing) Then
                Me.AtualizarDadosClienteVAOperationCompleted = AddressOf Me.OnAtualizarDadosClienteVAOperationCompleted
            End If
            Me.InvokeAsync("AtualizarDadosClienteVA", New Object() {oDados}, Me.AtualizarDadosClienteVAOperationCompleted, userState)
        End Sub
        
        Private Sub OnAtualizarDadosClienteVAOperationCompleted(ByVal arg As Object)
            If (Not (Me.AtualizarDadosClienteVACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AtualizarDadosClienteVACompleted(Me, New AtualizarDadosClienteVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaCnpjCpfClienteSubClienteVA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaCnpjCpfClienteSubClienteVA(ByVal IndicacaoCpfCnpj As Long, ByVal CnpjCpf As String) As RetornoConsulta
            Dim results() As Object = Me.Invoke("ConsultaCnpjCpfClienteSubClienteVA", New Object() {IndicacaoCpfCnpj, CnpjCpf})
            Return CType(results(0),RetornoConsulta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaCnpjCpfClienteSubClienteVAAsync(ByVal IndicacaoCpfCnpj As Long, ByVal CnpjCpf As String)
            Me.ConsultaCnpjCpfClienteSubClienteVAAsync(IndicacaoCpfCnpj, CnpjCpf, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaCnpjCpfClienteSubClienteVAAsync(ByVal IndicacaoCpfCnpj As Long, ByVal CnpjCpf As String, ByVal userState As Object)
            If (Me.ConsultaCnpjCpfClienteSubClienteVAOperationCompleted Is Nothing) Then
                Me.ConsultaCnpjCpfClienteSubClienteVAOperationCompleted = AddressOf Me.OnConsultaCnpjCpfClienteSubClienteVAOperationCompleted
            End If
            Me.InvokeAsync("ConsultaCnpjCpfClienteSubClienteVA", New Object() {IndicacaoCpfCnpj, CnpjCpf}, Me.ConsultaCnpjCpfClienteSubClienteVAOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaCnpjCpfClienteSubClienteVAOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaCnpjCpfClienteSubClienteVACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaCnpjCpfClienteSubClienteVACompleted(Me, New ConsultaCnpjCpfClienteSubClienteVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AtualizarDadosSubClienteVA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AtualizarDadosSubClienteVA(ByVal oDados As DadosWsSubCliente) As RetornoSubCliente
            Dim results() As Object = Me.Invoke("AtualizarDadosSubClienteVA", New Object() {oDados})
            Return CType(results(0),RetornoSubCliente)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AtualizarDadosSubClienteVAAsync(ByVal oDados As DadosWsSubCliente)
            Me.AtualizarDadosSubClienteVAAsync(oDados, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AtualizarDadosSubClienteVAAsync(ByVal oDados As DadosWsSubCliente, ByVal userState As Object)
            If (Me.AtualizarDadosSubClienteVAOperationCompleted Is Nothing) Then
                Me.AtualizarDadosSubClienteVAOperationCompleted = AddressOf Me.OnAtualizarDadosSubClienteVAOperationCompleted
            End If
            Me.InvokeAsync("AtualizarDadosSubClienteVA", New Object() {oDados}, Me.AtualizarDadosSubClienteVAOperationCompleted, userState)
        End Sub
        
        Private Sub OnAtualizarDadosSubClienteVAOperationCompleted(ByVal arg As Object)
            If (Not (Me.AtualizarDadosSubClienteVACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AtualizarDadosSubClienteVACompleted(Me, New AtualizarDadosSubClienteVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DadosWsCliente
        
        Private codigoClientePROFATField As System.Nullable(Of Integer)
        
        Private indicacaoCpfCnpjField As String
        
        Private cnpjCpfField As String
        
        Private situacaoClienteField As System.Nullable(Of Integer)
        
        Private razaoSocialField As String
        
        Private nomeAbreviadoField As String
        
        Private cEPField As String
        
        Private enderecoField As String
        
        Private numeroEnderecoField As String
        
        Private tipoLogradouroField As String
        
        Private complementoField As String
        
        Private bairroField As String
        
        Private cidadeField As String
        
        Private ufField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoClientePROFAT() As System.Nullable(Of Integer)
            Get
                Return Me.codigoClientePROFATField
            End Get
            Set
                Me.codigoClientePROFATField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IndicacaoCpfCnpj() As String
            Get
                Return Me.indicacaoCpfCnpjField
            End Get
            Set
                Me.indicacaoCpfCnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CnpjCpf() As String
            Get
                Return Me.cnpjCpfField
            End Get
            Set
                Me.cnpjCpfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SituacaoCliente() As System.Nullable(Of Integer)
            Get
                Return Me.situacaoClienteField
            End Get
            Set
                Me.situacaoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set
                Me.razaoSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeAbreviado() As String
            Get
                Return Me.nomeAbreviadoField
            End Get
            Set
                Me.nomeAbreviadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Endereco() As String
            Get
                Return Me.enderecoField
            End Get
            Set
                Me.enderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroEndereco() As String
            Get
                Return Me.numeroEnderecoField
            End Get
            Set
                Me.numeroEnderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Complemento() As String
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RetornoSubCliente
        
        Private codigoRetornoField As System.Nullable(Of Integer)
        
        Private codigoPontoAtendimentoField As System.Nullable(Of Integer)
        
        Private codigoPontoAtendimentoFieldSpecified As Boolean
        
        Private indicacaoCpfCnpjField As String
        
        Private cnpjCpfField As String
        
        Private insEstField As String
        
        Private insMunField As String
        
        Private situacaoPontoField As System.Nullable(Of Integer)
        
        Private situacaoPontoFieldSpecified As Boolean
        
        Private tipoPontoField As System.Nullable(Of Integer)
        
        Private tipoPontoFieldSpecified As Boolean
        
        Private razaoSocialField As String
        
        Private cEPField As String
        
        Private enderecoField As String
        
        Private numeroEnderecoField As String
        
        Private tipoLogradouroField As String
        
        Private bairroField As String
        
        Private cidadeField As String
        
        Private ufField As String
        
        Private complementoField As String
        
        Private emailField As String
        
        Private destinatarioField As String
        
        Private departamentoField As String
        
        Private nomeResponsavelEmailField As String
        
        Private lista_RetornoField() As Mensagens
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoRetorno() As System.Nullable(Of Integer)
            Get
                Return Me.codigoRetornoField
            End Get
            Set
                Me.codigoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoPontoAtendimento() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPontoAtendimentoField
            End Get
            Set
                Me.codigoPontoAtendimentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CodigoPontoAtendimentoSpecified() As Boolean
            Get
                Return Me.codigoPontoAtendimentoFieldSpecified
            End Get
            Set
                Me.codigoPontoAtendimentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IndicacaoCpfCnpj() As String
            Get
                Return Me.indicacaoCpfCnpjField
            End Get
            Set
                Me.indicacaoCpfCnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CnpjCpf() As String
            Get
                Return Me.cnpjCpfField
            End Get
            Set
                Me.cnpjCpfField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InsEst() As String
            Get
                Return Me.insEstField
            End Get
            Set
                Me.insEstField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InsMun() As String
            Get
                Return Me.insMunField
            End Get
            Set
                Me.insMunField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SituacaoPonto() As System.Nullable(Of Integer)
            Get
                Return Me.situacaoPontoField
            End Get
            Set
                Me.situacaoPontoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SituacaoPontoSpecified() As Boolean
            Get
                Return Me.situacaoPontoFieldSpecified
            End Get
            Set
                Me.situacaoPontoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TipoPonto() As System.Nullable(Of Integer)
            Get
                Return Me.tipoPontoField
            End Get
            Set
                Me.tipoPontoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TipoPontoSpecified() As Boolean
            Get
                Return Me.tipoPontoFieldSpecified
            End Get
            Set
                Me.tipoPontoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set
                Me.razaoSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Endereco() As String
            Get
                Return Me.enderecoField
            End Get
            Set
                Me.enderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroEndereco() As String
            Get
                Return Me.numeroEnderecoField
            End Get
            Set
                Me.numeroEnderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Complemento() As String
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Destinatario() As String
            Get
                Return Me.destinatarioField
            End Get
            Set
                Me.destinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Departamento() As String
            Get
                Return Me.departamentoField
            End Get
            Set
                Me.departamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeResponsavelEmail() As String
            Get
                Return Me.nomeResponsavelEmailField
            End Get
            Set
                Me.nomeResponsavelEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lista_Retorno() As Mensagens()
            Get
                Return Me.lista_RetornoField
            End Get
            Set
                Me.lista_RetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Mensagens
        
        Private codigoField As String
        
        Private mensagemField As String
        
        Private detalheField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Detalhe() As String
            Get
                Return Me.detalheField
            End Get
            Set
                Me.detalheField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DadosWsSubCliente
        
        Private codigoPontoAtendimentoField As System.Nullable(Of Integer)
        
        Private indicacaoCpfCnpjField As String
        
        Private cnpjCpfField As String
        
        Private insEstField As String
        
        Private insMunField As String
        
        Private situacaoPontoField As System.Nullable(Of Integer)
        
        Private tipoPontoField As System.Nullable(Of Integer)
        
        Private razaoSocialField As String
        
        Private cEPField As String
        
        Private enderecoField As String
        
        Private numeroEnderecoField As String
        
        Private tipoLogradouroField As String
        
        Private bairroField As String
        
        Private cidadeField As String
        
        Private ufField As String
        
        Private complementoField As String
        
        Private emailField As String
        
        Private destinatarioField As String
        
        Private departamentoField As String
        
        Private nomeResponsavelEmailField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoPontoAtendimento() As System.Nullable(Of Integer)
            Get
                Return Me.codigoPontoAtendimentoField
            End Get
            Set
                Me.codigoPontoAtendimentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IndicacaoCpfCnpj() As String
            Get
                Return Me.indicacaoCpfCnpjField
            End Get
            Set
                Me.indicacaoCpfCnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CnpjCpf() As String
            Get
                Return Me.cnpjCpfField
            End Get
            Set
                Me.cnpjCpfField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InsEst() As String
            Get
                Return Me.insEstField
            End Get
            Set
                Me.insEstField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InsMun() As String
            Get
                Return Me.insMunField
            End Get
            Set
                Me.insMunField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SituacaoPonto() As System.Nullable(Of Integer)
            Get
                Return Me.situacaoPontoField
            End Get
            Set
                Me.situacaoPontoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TipoPonto() As System.Nullable(Of Integer)
            Get
                Return Me.tipoPontoField
            End Get
            Set
                Me.tipoPontoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set
                Me.razaoSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Endereco() As String
            Get
                Return Me.enderecoField
            End Get
            Set
                Me.enderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroEndereco() As String
            Get
                Return Me.numeroEnderecoField
            End Get
            Set
                Me.numeroEnderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Complemento() As String
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Destinatario() As String
            Get
                Return Me.destinatarioField
            End Get
            Set
                Me.destinatarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Departamento() As String
            Get
                Return Me.departamentoField
            End Get
            Set
                Me.departamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeResponsavelEmail() As String
            Get
                Return Me.nomeResponsavelEmailField
            End Get
            Set
                Me.nomeResponsavelEmailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RetornoConsulta
        
        Private codigoRetornoField As System.Nullable(Of Integer)
        
        Private codigoClienteField As String
        
        Private codigoSitClienteField As String
        
        Private codigoNfEmitidaField As String
        
        Private codPonAteField As String
        
        Private codSitPonField As String
        
        Private codTipPonField As String
        
        Private codigoNfEmitidaSubClienteField As String
        
        Private lista_RetornoField() As Mensagens
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoRetorno() As System.Nullable(Of Integer)
            Get
                Return Me.codigoRetornoField
            End Get
            Set
                Me.codigoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoCliente() As String
            Get
                Return Me.codigoClienteField
            End Get
            Set
                Me.codigoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoSitCliente() As String
            Get
                Return Me.codigoSitClienteField
            End Get
            Set
                Me.codigoSitClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoNfEmitida() As String
            Get
                Return Me.codigoNfEmitidaField
            End Get
            Set
                Me.codigoNfEmitidaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodPonAte() As String
            Get
                Return Me.codPonAteField
            End Get
            Set
                Me.codPonAteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodSitPon() As String
            Get
                Return Me.codSitPonField
            End Get
            Set
                Me.codSitPonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodTipPon() As String
            Get
                Return Me.codTipPonField
            End Get
            Set
                Me.codTipPonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoNfEmitidaSubCliente() As String
            Get
                Return Me.codigoNfEmitidaSubClienteField
            End Get
            Set
                Me.codigoNfEmitidaSubClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lista_Retorno() As Mensagens()
            Get
                Return Me.lista_RetornoField
            End Get
            Set
                Me.lista_RetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Retorno
        
        Private codigoRetornoField As System.Nullable(Of Integer)
        
        Private codigoClientePROFATField As System.Nullable(Of Integer)
        
        Private codigoClientePROFATFieldSpecified As Boolean
        
        Private indicacaoCpfCnpjField As String
        
        Private cnpjCpfField As String
        
        Private situacaoClienteField As System.Nullable(Of Integer)
        
        Private situacaoClienteFieldSpecified As Boolean
        
        Private razaoSocialField As String
        
        Private nomeAbreviadoField As String
        
        Private cEPField As String
        
        Private enderecoField As String
        
        Private numeroEnderecoField As String
        
        Private tipoLogradouroField As String
        
        Private complementoField As String
        
        Private bairroField As String
        
        Private cidadeField As String
        
        Private ufField As String
        
        Private lista_RetornoField() As Mensagens
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoRetorno() As System.Nullable(Of Integer)
            Get
                Return Me.codigoRetornoField
            End Get
            Set
                Me.codigoRetornoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodigoClientePROFAT() As System.Nullable(Of Integer)
            Get
                Return Me.codigoClientePROFATField
            End Get
            Set
                Me.codigoClientePROFATField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CodigoClientePROFATSpecified() As Boolean
            Get
                Return Me.codigoClientePROFATFieldSpecified
            End Get
            Set
                Me.codigoClientePROFATFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IndicacaoCpfCnpj() As String
            Get
                Return Me.indicacaoCpfCnpjField
            End Get
            Set
                Me.indicacaoCpfCnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CnpjCpf() As String
            Get
                Return Me.cnpjCpfField
            End Get
            Set
                Me.cnpjCpfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SituacaoCliente() As System.Nullable(Of Integer)
            Get
                Return Me.situacaoClienteField
            End Get
            Set
                Me.situacaoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SituacaoClienteSpecified() As Boolean
            Get
                Return Me.situacaoClienteFieldSpecified
            End Get
            Set
                Me.situacaoClienteFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set
                Me.razaoSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeAbreviado() As String
            Get
                Return Me.nomeAbreviadoField
            End Get
            Set
                Me.nomeAbreviadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CEP() As String
            Get
                Return Me.cEPField
            End Get
            Set
                Me.cEPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Endereco() As String
            Get
                Return Me.enderecoField
            End Get
            Set
                Me.enderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroEndereco() As String
            Get
                Return Me.numeroEnderecoField
            End Get
            Set
                Me.numeroEnderecoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoLogradouro() As String
            Get
                Return Me.tipoLogradouroField
            End Get
            Set
                Me.tipoLogradouroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Complemento() As String
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set
                Me.bairroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cidade() As String
            Get
                Return Me.cidadeField
            End Get
            Set
                Me.cidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UF() As String
            Get
                Return Me.ufField
            End Get
            Set
                Me.ufField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lista_Retorno() As Mensagens()
            Get
                Return Me.lista_RetornoField
            End Get
            Set
                Me.lista_RetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub AtualizarDadosClienteVACompletedEventHandler(ByVal sender As Object, ByVal e As AtualizarDadosClienteVACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AtualizarDadosClienteVACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Retorno
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Retorno)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub ConsultaCnpjCpfClienteSubClienteVACompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaCnpjCpfClienteSubClienteVACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaCnpjCpfClienteSubClienteVACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RetornoConsulta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RetornoConsulta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")>  _
    Public Delegate Sub AtualizarDadosSubClienteVACompletedEventHandler(ByVal sender As Object, ByVal e As AtualizarDadosSubClienteVACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AtualizarDadosSubClienteVACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RetornoSubCliente
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RetornoSubCliente)
            End Get
        End Property
    End Class
End Namespace
