MERGE INTO MARTE.COPR_TFILIAL_COM_X_FAT FAT 
 USING (SELECT 'PAR1' COD_FILIAL_COMERCIAL
              ,'PAR2' COD_EMPRESA_COMERCIAL
              ,'PAR3' COD_FILIAL_FACTURACION
        FROM dual) COD 
 ON (COD.COD_FILIAL_COMERCIAL = FAT.COD_FILIAL_COMERCIAL 
     AND COD.COD_EMPRESA_COMERCIAL = FAT.COD_EMPRESA_COMERCIAL
     AND COD.COD_FILIAL_FACTURACION = FAT.COD_FILIAL_FACTURACION)
 WHEN MATCHED THEN 
      UPDATE SET FYH_MDATE = SYSDATE, DES_MUID = 'OM13'
 WHEN NOT MATCHED THEN 
      INSERT (COD_FILIAL_COMERCIAL, COD_EMPRESA_COMERCIAL, COD_FILIAL_FACTURACION, FYH_MDATE, DES_MUID)
      VALUES (COD.COD_FILIAL_COMERCIAL,COD.COD_EMPRESA_COMERCIAL, COD.COD_FILIAL_FACTURACION, SYSDATE, 'OM13')