MERGE INTO MARTE.COPR_TCAD_FILIAL_FAT FAT 
 USING (SELECT 'PAR1' COD_FILIAL
			  ,'PAR2' DES_FILIAL
			  ,'PAR3' COD_CNPJ
        FROM DUAL) COD 
 ON (COD.COD_FILIAL = FAT.COD_FILIAL 
     AND COD.DES_FILIAL = FAT.DES_FILIAL
     AND COD.COD_CNPJ = FAT.COD_CNPJ)
 WHEN MATCHED THEN 
      UPDATE SET FYH_MDATE = SYSDATE, DES_MUID = 'OM13'
 WHEN NOT MATCHED THEN 
      INSERT (COD_FILIAL, DES_FILIAL, COD_CNPJ, FYH_MDATE, DES_MUID)
      VALUES (COD.COD_FILIAL, COD.DES_FILIAL, COD.COD_CNPJ, SYSDATE, 'OM13')