INSERT INTO DDLVIG.ODERE
SELECT DISTINCT 'OM13' ODERE_USU_ULTACTU , TO_CHAR(SYSDATE, 'YYYYMMDD') ODERE_FEC_ULTACTU , 
       TO_CHAR(SYSDATE, 'HH24MISS') ODERE_HOR_ULTACTU, REG.OREGI_COD_REG ODERE_COD_REG , V.COD_NOVI ODERE_COD_DELEG 
FROM MARTE.COPR_TFILIAL F INNER JOIN MARTE.COPR_TDELEGACION D ON F.OID_DELEGACION = D.OID_DELEGACION
  INNER JOIN ADA_OREGI REG ON D.COD_DELEGACION = REG.OREGI_COD_REG
  INNER JOIN MARTE.VABR_TDE_PARA_GERAL V ON F.COD_FILIAL = V.COD_MARTE
  INNER JOIN DDLVIG.ODELE O ON O.ODELE_COD_DELEG = V.COD_NOVI
WHERE V.COD_PARAM_TAB IN('4','13')
ORDER BY REG.OREGI_COD_REG