UPDATE DDLVIG.ODELE
SET COD_FILIAL_COMERCIAL = :COD_COMERCIAL,
	ODELE_USU_ULTACTU = 'OM13',
	ODELE_FEC_ULTACTU = TO_CHAR(SYSDATE, 'YYYYMMDD'),
	ODELE_HOR_ULTACTU = TO_CHAR(SYSDATE, 'HH24MISS')
WHERE ODELE_COD_DELEG = :COD_NOVI