MERGE INTO MARTE.COPR_TSUBSEGMENTO SEG1
 USING (SELECT 'PAR1' COD_SUBSEGMENTO, 'PAR2' DES_SUBSEGMENTO, 'PAR3' COD_SUBSEGMENTO_PROFAT, 'PAR4' OID_SEGMENTO, 'PAR5' OID_SUBSEGMENTO FROM DUAL) SEG2 
 ON (SEG1.OID_SUBSEGMENTO = SEG2.OID_SUBSEGMENTO)
 WHEN MATCHED THEN 
      UPDATE SET COD_SUBSEGMENTO  = SEG2.COD_SUBSEGMENTO_PROFAT, 
                 DES_SUBSEGMENTO   = SEG2.DES_SUBSEGMENTO, 
                 BOL_ACTIVO  = 1
 WHEN NOT MATCHED THEN 
      INSERT (OID_SUBSEGMENTO, OID_SEGMENTO, COD_SUBSEGMENTO, DES_SUBSEGMENTO, BOL_ACTIVO)
      VALUES ('PAR6', SEG2.OID_SEGMENTO, SEG2.COD_SUBSEGMENTO_PROFAT, SEG2.DES_SUBSEGMENTO, 1)