MERGE INTO MARTE.COPR_TSEGMENTO SEG1
 USING (SELECT 'PAR1' COD_SEGMENTO, 'PAR2' DES_SEGMENTO , 'PAR3' COD_SEGMENTO_PROFAT, 'PAR4' OID_SEGMENTO FROM DUAL) SEG2 
 ON (SEG1.OID_SEGMENTO = SEG2.OID_SEGMENTO)
 WHEN MATCHED THEN 
      UPDATE SET COD_SEGMENTO = SEG2.COD_SEGMENTO_PROFAT, 
                 DES_SEGMENTO  = SEG2.DES_SEGMENTO, 
                 BOL_ACTIVO = 1
 WHEN NOT MATCHED THEN 
      INSERT (OID_SEGMENTO, COD_SEGMENTO, DES_SEGMENTO, BOL_ACTIVO, FYH_CDATE, DES_CUID)
      VALUES ('PAR5', SEG2.COD_SEGMENTO_PROFAT, SEG2.DES_SEGMENTO, 1, SYSDATE, 'OM13')