SELECT S.CODRAMATV, S.DESRAMATV, SUB.CODSUBRAMATV, SUB.DESSUBRAMATV
FROM FAT_TTABRELRAMATV AS J WITH(NOLOCK) 
	 INNER JOIN FAT_TTABRAMATV AS S WITH(NOLOCK) ON J.CODRAMATV = S.CODRAMATV
	 INNER JOIN FAT_TTABSUBRAMATV AS SUB WITH(NOLOCK) ON J.CODSUBRAMATV = SUB.CODSUBRAMATV
ORDER BY J.CODRAMATV, J.CODSUBRAMATV