SELECT S.OID_SEGMENTO, S.COD_SEGMENTO, S.DES_SEGMENTO,
       SUB.OID_SUBSEGMENTO, SUB.COD_SUBSEGMENTO, SUB.DES_SUBSEGMENTO
FROM MARTE.COPR_TSEGMENTO S 
     INNER JOIN MARTE.COPR_TSUBSEGMENTO SUB ON S.OID_SEGMENTO = SUB.OID_SEGMENTO
WHERE 0=0
  {0}